export const GET_SONG_DETAIL ='GET_SONG_DETAIL'

export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'

export const CHANGE_CURRENT_INDEX = 'CHANGE_CURRENT_INDEX '

export const CHANGE_SEQUENCE = 'CHANGE_SEQUENCE'

export const CHANGE_LYRIC_LIST = "CHANGE_LYRIC_LIST";
export const CHANGE_CURRENT_LYRIC_INDEX = "CHANGE_CURRENT_LYRIC_INDEX ";